### ISSUE TITLE
Goroutine leak 

### ISSUE THREAD

**Issue by navneetk** [googollee/go-engine.io#46]
After running the server for close to a month, i noticed that the server memory consumption was increasing. Did a quick go pprof and found that some connections might not have been closed properly and the goroutine hangs trying to send on the unbuffered channel.

`server_conn.go:231:
c.readerChan <- newConnReader(r, closeChan)
`

```goroutine profile: total 13629
6462 @ 0x438e6a 0x438f5e 0x40fc78 0x40fa3d 0x7df980 0x87cd48 0x469d21
#	0x7df97f	github.com/googollee/go-engine%2eio.(*serverConn).OnPacket+0x5ff	/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/server_conn.go:231
#	0x87cd47	github.com/googollee/go-engine.io/websocket.(*Server).serveHTTP+0xd7	/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/websocket/server.go:77
```

```
5854 @ 0x438e6a 0x438f5e 0x40fc78 0x40fa3d 0x7df980 0x87b059 0x87a37c 0x7df307 0x7dd8ae 0x67facd 0x53b56b 0x4c2fef 0x4c39fd 0x4c0487 0x469d21
#	0x7df97f	github.com/googollee/go-engine%2eio.(*serverConn).OnPacket+0x5ff	/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/server_conn.go:231
#	0x87b058	github.com/googollee/go-engine.io/polling.(*Polling).post+0x2a8		/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/polling/server.go:181
#	0x87a37b	github.com/googollee/go-engine.io/polling.(*Polling).ServeHTTP+0xab	/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/polling/server.go:55
#	0x7df306	github.com/googollee/go-engine%2eio.(*serverConn).ServeHTTP+0x3e6	/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/server_conn.go:198
#	0x7dd8ad	github.com/googollee/go-engine%2eio.(*Server).ServeHTTP+0x1ad		/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/server.go:159
#	0x67facc	github.com/googollee/go-socket%2eio.(*Server).ServeHTTP+0x4c		/home/navneet/repo/_vendor/src/github.com/googollee/go-socket.io/server.go:87
#	0x53b56a	hub.webSocketServer.ServeHTTP+0x16a					/home/navneet/repo/src/hub/websocketserver.go:286
#	0x4c2fee	net/http.(*ServeMux).ServeHTTP+0x7e					/home/navneet/go/go.1.7.1/src/net/http/server.go:2022
#	0x4c39fc	net/http.serverHandler.ServeHTTP+0x7c					/home/navneet/go/go.1.7.1/src/net/http/server.go:2202
#	0x4c0486	net/http.(*conn).serve+0x4b6						/home/navneet/go/go.1.7.1/src/net/http/server.go:1579
```

After the server was running for close to a month we see that 6462 and 5854 are stuck waiting to write to the channel. It happens for both polling and websocket connections.

```
goroutine 8788296 [chan send, 30612 minutes]:
github.com/googollee/go-engine%2eio.(*serverConn).OnPacket(0xc42feb3040, 0xc42fa5f280)	/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/server_conn.go:231 +0x600
github.com/googollee/go-engine.io/polling.(*Polling).post(0xc43065a300, 0x11912a0, 0xc42fa208f0, 0xc432097860)	/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/polling/server.go:181 +0x2a9
github.com/googollee/go-engine.io/polling.(*Polling).ServeHTTP(0xc43065a300, 0x11912a0, 0xc42fa208f0, 0xc432097860) /home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/polling/server.go:55 +0xac
github.com/googollee/go-engine%2eio.(*serverConn).ServeHTTP(0xc42feb3040, 0x11912a0, 0xc42fa208f0, 0xc432097860)	/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/server_conn.go:198 +0x3e7
github.com/googollee/go-engine%2eio.(*Server).ServeHTTP(0xc42004eb60, 0x11912a0, 0xc42fa208f0, 0xc432097860)	/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/server.go:159 +0x1ae
github.com/googollee/go-socket%2eio.(*Server).ServeHTTP(0xc4200b9a60, 0x11912a0, 0xc42fa208f0, 0xc432097860)	/home/navneet/repo/_vendor/src/github.com/googollee/go-socket.io/server.go:87 +0x4d
hub.webSocketServer.ServeHTTP(0xc4200b9a60, 0x11912a0, 0xc42fa208f0, 0xc432097860)	/home/navneet/repo/src/hub/websocketserver.go:286 +0x16b
net/http.(*ServeMux).ServeHTTP(0x11ab7a0, 0x11912a0, 0xc42fa208f0, 0xc432097860)	/home/navneet/go/go.1.7.1/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420113280, 0x11912a0, 0xc42fa208f0, 0xc432097860)	/home/navneet/go/go.1.7.1/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42ea25c00, 0x11922e0, 0xc42fa5f180)	/home/navneet/go/go.1.7.1/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve	/home/navneet/go/go.1.7.1/src/net/http/server.go:2293 +0x44d
```

The number of connections during this time was around 400. Which is reflected by the these goroutines.

```
413 @ 0x438e6a 0x438f5e 0x41096f 0x410635 0x7de942 0x67dc53 0x680764 0x680feb 0x469d21
#	0x7de941	github.com/googollee/go-engine%2eio.(*serverConn).NextReader+0x71	/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/server_conn.go:128
#	0x67dc52	github.com/googollee/go-socket%2eio.(*decoder).Decode+0x62		/home/navneet/repo/_vendor/src/github.com/googollee/go-socket.io/parser.go:169
#	0x680763	github.com/googollee/go-socket%2eio.(*socket).loop+0x2c3		/home/navneet/repo/_vendor/src/github.com/googollee/go-socket.io/socket.go:132
#	0x680fea	github.com/googollee/go-socket%2eio.(*Server).loop.func1+0x2a		/home/navneet/repo/_vendor/src/github.com/googollee/go-socket.io/server.go:103

399 @ 0x438e6a 0x448479 0x44726c 0x7e0d35 0x469d21
#	0x7e0d34	github.com/googollee/go-engine%2eio.(*serverConn).pingLoop+0x3d4	/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/server_conn.go:361

388 @ 0x438e6a 0x43375b 0x432eb9 0x5eaea8 0x5eaf14 0x5ec751 0x5fd9c0 0x631c1c 0x63227c 0xa3084d 0xa30996 0xa31bc7 0x87cce4 0x469d21
#	0x432eb8	net.runtime_pollWait+0x58						/home/navneet/go/go.1.7.1/src/runtime/netpoll.go:160
#	0x5eaea7	net.(*pollDesc).wait+0x37						/home/navneet/go/go.1.7.1/src/net/fd_poll_runtime.go:73
#	0x5eaf13	net.(*pollDesc).waitRead+0x33						/home/navneet/go/go.1.7.1/src/net/fd_poll_runtime.go:78
#	0x5ec750	net.(*netFD).Read+0x1a0							/home/navneet/go/go.1.7.1/src/net/fd_unix.go:243
#	0x5fd9bf	net.(*conn).Read+0x6f							/home/navneet/go/go.1.7.1/src/net/net.go:173
#	0x631c1b	bufio.(*Reader).fill+0x10b						/home/navneet/go/go.1.7.1/src/bufio/bufio.go:97
#	0x63227b	bufio.(*Reader).Read+0x1bb						/home/navneet/go/go.1.7.1/src/bufio/bufio.go:209
#	0xa3084c	github.com/gorilla/websocket.(*Conn).readFull+0x8c			/home/navneet/repo/_vendor/src/github.com/gorilla/websocket/conn.go:643
#	0xa30995	github.com/gorilla/websocket.(*Conn).advanceFrame+0x95			/home/navneet/repo/_vendor/src/github.com/gorilla/websocket/conn.go:667
#	0xa31bc6	github.com/gorilla/websocket.(*Conn).NextReader+0x56			/home/navneet/repo/_vendor/src/github.com/gorilla/websocket/conn.go:812
#	0x87cce3	github.com/googollee/go-engine.io/websocket.(*Server).serveHTTP+0x73	/home/navneet/repo/_vendor/src/github.com/googollee/go-engine.io/websocket/server.go:63
```

A check on the number of File Descriptors held by the process revealed that the old socket connections have not been released.

**Comment by erkie** [comment]
Closing this issue because it is so old and has probably been fixed by now. If you are still having issues feel free to let me know and I can reopen it for you.
