### ISSUE TITLE
send on closed channel && close of closed channel

### ISSUE THREAD

**Issue by ruandao** [googollee/go-engine.io#47]
```
1976513-panic: send on closed channel
1976514-
1976515:goroutine 338071 [running]:
1976516-panic(0x83ad60, 0xc829f05840)
1976517-	/usr/local/go/src/runtime/panic.go:464 +0x3e6
1976518-github.com/googollee/go-engine%2eio.(*serverConn).OnPacket(0xc82739d450, 0xc82850c600)
1976519-	/data/html/live_im_system/src/github.com/googollee/go-engine.io/server_conn.go:228 +0x488
1976520-github.com/googollee/go-engine.io/websocket.(*Server).serveHTTP(0xc8289f3620, 0x7fbc704ba510, 0xc8273581a0, 0xc8273fad20)
1976521-	/data/html/live_im_system/src/github.com/googollee/go-engine.io/websocket/server.go:77 +0x196
1976522-created by github.com/googollee/go-engine.io/websocket.NewServer
1976523-	/data/html/live_im_system/src/github.com/googollee/go-engine.io/websocket/server.go:29 +0x16d
```

**Comment by ruandao** [comment]
```
panic: close of closed channel

goroutine 500621 [running]:
panic(0x83ad60, 0xc82b1472f0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/googollee/go-engine%2eio.(*serverConn).OnClose(0xc82bd09790, 0x7f211aa30ee0, 0xc826105840)
        /data/html/live_im_system/src/github.com/googollee/go-engine.io/server_conn.go:257 +0x1a2
github.com/googollee/go-engine.io/polling.(*Polling).Close(0xc826105840, 0x0, 0x0)
        /data/html/live_im_system/src/github.com/googollee/go-engine.io/polling/server.go:67 +0x115
github.com/googollee/go-engine%2eio.(*serverConn).Close(0xc82bd09790, 0x0, 0x0)
        /data/html/live_im_system/src/github.com/googollee/go-engine.io/server_conn.go:176 +0x217
github.com/googollee/go-engine%2eio.(*serverConn).pingLoop(0xc82bd09790)
        /data/html/live_im_system/src/github.com/googollee/go-engine.io/server_conn.go:384 +0x416
created by github.com/googollee/go-engine%2eio.newServerConn
        /data/html/live_im_system/src/github.com/googollee/go-engine.io/server_conn.go:112 +0x58e
```

**Comment by erkie** [comment]
Found a possible culprit in this discussion:
https://github.com/googollee/go-engine.io/pull/63

**Comment by exapsy** [comment]
I'm using gorilla/mux, I'm not sure if this is the reason.

But I think it's a race issue. If the server hasn't yet opened, then the channel has never opened, thus the channel is closed, which throws this error.

**Solution**

Initiate the socket.io server ASAP? I used `http` to immediately serve the Socket.IO handler instead of using gorilla/mux which might call a bunch of other things before initializing the server.

I'm not 100% sure over this case, but I'll reinvestigate when I'll have enough time.
