### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by wenzhenxi** [googollee/go-engine.io#53]
panic: close of closed channel

goroutine 314515 [running]:
sunmi-socket.io/vendor/github.com/googollee/go-engine%2eio.(*serverConn).OnClose(0xc4bbe5edd0, 0xb8a5a0, 0xc4bbd45400)
        /app/go/src/sunmi-socket.io/vendor/github.com/googollee/go-engine.io/server_conn.go:261 +0x110
sunmi-socket.io/vendor/github.com/googollee/go-engine.io/polling.(*Polling).Close(0xc4bbd45400, 0xb8a5a0, 0xc4bbd45400)
        /app/go/src/sunmi-socket.io/vendor/github.com/googollee/go-engine.io/polling/server.go:67 +0x10c
sunmi-socket.io/vendor/github.com/googollee/go-engine%2eio.(*serverConn).Close(0xc4bbe5edd0, 0xc53f8d5c20, 0x0)
        /app/go/src/sunmi-socket.io/vendor/github.com/googollee/go-engine.io/server_conn.go:175 +0xfe
sunmi-socket.io/vendor/github.com/googollee/go-engine%2eio.(*serverConn).pingLoop(0xc4bbe5edd0)
        /app/go/src/sunmi-socket.io/vendor/github.com/googollee/go-engine.io/server_conn.go:384 +0x39f
created by sunmi-socket.io/vendor/github.com/googollee/go-engine%2eio.newServerConn
        /app/go/src/sunmi-socket.io/vendor/github.com/googollee/go-engine.io/server_conn.go:111 +0x3f4

**Comment by erkie** [comment]
Got this twice in the last two days too. Never seen it before.

```
github.com/app/myapp/vendor/github.com/googollee/go-engine.io/polling.(*Writer).Close(0xc42c11bac0, 0xbce988, 0xc42c11bae0)
	/home/app/src/github.com/app/myapp/vendor/github.com/googollee/go-engine.io/polling/writer.go:29 +0xcf
github.com/app/myapp/vendor/github.com/googollee/go-engine%2eio.(*connWriter).Close(0xc42c11bae0, 0x0, 0x0)
	/home/app/src/github.com/app/myapp/vendor/github.com/googollee/go-engine.io/ioutil.go:49 +0x6f
github.com/app/myapp/vendor/github.com/googollee/go-socket%2eio.(*encoder).encodePacket(0xc4962ebe98, 0x0, 0x0, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/app/src/github.com/app/myapp/vendor/github.com/googollee/go-socket.io/parser.go:130 +0x554
github.com/app/myapp/vendor/github.com/googollee/go-socket%2eio.(*encoder).Encode(0xc43ff63e98, 0x0, 0x0, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0xc446cc6140, 0xc4962ebef0)
	/home/app/src/github.com/app/myapp/vendor/github.com/googollee/go-socket.io/parser.go:82 +0xb2
github.com/app/myapp/vendor/github.com/googollee/go-socket%2eio.(*socket).loop(0xc44ca5a380, 0x0, 0x0)
	/home/app/src/github.com/app/myapp/vendor/github.com/googollee/go-socket.io/socket.go:137 +0x1d0
github.com/app/myapp/vendor/github.com/googollee/go-socket%2eio.(*Server).loop.func1(0xc44ca5a380)
	/home/app/src/github.com/app/myapp/vendor/github.com/googollee/go-socket.io/server.go:103 +0x2b
created by github.com/app/myapp/vendor/github.com/googollee/go-socket%2eio.(*Server).loop
	/home/app/src/github.com/app/myapp/vendor/github.com/googollee/go-socket.io/server.go:102 +0x9d
```

**Comment by erkie** [comment]
@googollee do you have any ideas what could be happening?

**Comment by erkie** [comment]
From the looks of the stacktrace, it appears that a panic is caused somewhere, causing a `defer`'d call of something to close something in a way that the rest of the code does not expect.

I followed the stacktrace and found one scenario where a function would return a nil value, which could be responsible for the panic.

Attached is my changelog, I'll try it out now for a couple of days to see if I get the error again.

<img width="1005" alt="screenshot 2018-01-26 17 42 54" src="https://user-images.githubusercontent.com/21059/35450504-8599dff4-02c0-11e8-9b2d-e1b19508d5ff.png">

**Comment by erkie** [comment]
After releasing this I still got the same error. Continuing down the rabbit hole!

**Comment by erkie** [comment]
Think I found a case where the sanity check in https://github.com/googollee/go-engine.io/blob/master/polling/writer.go#L25 could fail because of a race condition. the `w.server.sendChan` that is `closed()` the only case where it was closed was in https://github.com/googollee/go-engine.io/blob/master/polling/server.go#L63. If you check you can see that it sets the state to "closing" AFTER it actually closes the channel. So my fix was to flip the two around. I've deployed that and will let it run for a couple of days to see if I get the error again.

<img width="607" alt="screenshot 2018-01-27 13 43 10" src="https://user-images.githubusercontent.com/21059/35472090-0edf7d98-0369-11e8-84a9-428beff2afeb.png">

**Comment by erkie** [comment]
OK, so got an error now. It seems to have morphed into a more interesting error message now at least:

```
panic: close of closed channel
goroutine 24450780 [running]:
github.com/app/myapp/vendor/github.com/googollee/go-engine%2eio.(*serverConn).OnClose(0xc43e3ce4e0, 0x102a9c0, 0xc45f741ac0)
        /home/app/golang/src/github.com/app/myapp/vendor/github.com/googollee/go-engine.io/server_conn.go:261 +0xfa
github.com/app/myapp/vendor/github.com/googollee/go-engine.io/polling.(*Polling).Close(0xc45f741ac0, 0x102a9c0, 0xc45f741ac0)
        /home/app/golang/src/github.com/app/myapp/vendor/github.com/googollee/go-engine.io/polling/server.go:67 +0x100
github.com/app/myapp/vendor/github.com/googollee/go-engine%2eio.(*serverConn).Close(0xc43e3ce4e0, 0x2, 0x0)
        /home/app/golang/src/github.com/app/myapp/vendor/github.com/googollee/go-engine.io/server_conn.go:175 +0xfe
github.com/app/myapp/vendor/github.com/googollee/go-engine%2eio.(*serverConn).pingLoop(0xc43e3ce4e0)
        /home/app/golang/src/github.com/app/myapp/vendor/github.com/googollee/go-engine.io/server_conn.go:384 +0x3d4
created by github.com/app/myapp/vendor/github.com/googollee/go-engine%2eio.newServerConn
        /home/app/golang/src/github.com/app/myapp/vendor/github.com/googollee/go-engine.io/server_conn.go:111 +0x3f4
```

The error is still originating from the same type of event, but this time it's getting further and crashing on another channel. I'm not sure why this is happening just in the "polling" transport, could it be when upgrading a connection to from polling to websocket?

When looking at https://github.com/googollee/go-engine.io/blob/master/server_conn.go#L261 the only place `readChan` is every closed is in that same method. So is it because somehow `OnClose` is being called multiple times? Will deep dive...

**Comment by erkie** [comment]
Final update for tonight: It seems to be related to upgrading logic. My guess is maybe https://github.com/googollee/go-engine.io/blob/master/server_conn.go#L255 or https://github.com/googollee/go-engine.io/blob/master/server_conn.go#L257 can call cause recursion if the `c.getUpgrade` returns itself? Or could it be https://github.com/googollee/go-engine.io/blob/master/server_conn.go#L252 fails when it shouldn't?

**Comment by erkie** [comment]
FYI, the number of errors occurred reduced dramatically after implementing my fix. Hopefully I can make a PR out of it, otherwise anyone reading this is free to do it :)
