### ISSUE TITLE
panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by tdaajames** [googollee/go-engine.io#74]
occasionally panic as below

panic: concurrent write to websocket connection

goroutine 3475 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0003d87e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/gopath/src/github.com/gorilla/websocket/conn.go:597 +0xac3
github.com/gorilla/websocket.(*messageWriter).Close(0xc0003d87e0, 0x0, 0x0)
	/home/gopath/src/github.com/gorilla/websocket/conn.go:711 +0x80
github.com/gorilla/websocket.(*Conn).beginMessage(0xc0004b0c60, 0xc00011e4b0, 0x1, 0x0, 0x0)
	/home/gopath/src/github.com/gorilla/websocket/conn.go:460 +0x71
github.com/gorilla/websocket.(*Conn).NextWriter(0xc0004b0c60, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/gopath/src/github.com/gorilla/websocket/conn.go:500 +0xb0
github.com/googollee/go-engine.io/transport/websocket.wrapper.NextWriter(0xc0004b0c60, 0x418800, 0x0, 0x0, 0x0, 0x0)
	/home/gopath/src/github.com/googollee/go-engine.io/transport/websocket/wrapper.go:47 +0x9b
github.com/googollee/go-engine.io/packet.(*encoder).NextWriter(0xc0001da0c0, 0x7f31c89c6f00, 0x3, 0x0, 0x0, 0x0, 0x0)
	/home/gopath/src/github.com/googollee/go-engine.io/packet/encoder.go:20 +0x81
github.com/googollee/go-engine%2eio.(*session).nextWriter(0xc00029f130, 0x0, 0x3, 0x0, 0x0, 0x0, 0x0)
	/home/gopath/src/github.com/googollee/go-engine.io/session.go:155 +0xb8
github.com/googollee/go-engine%2eio.(*session).NextReader.func1(0xc00029f130, 0x1002d00, 0x11533c0, 0xc00011e420, 0x0, 0x0)
	/home/gopath/src/github.com/googollee/go-engine.io/session.go:78 +0x73
github.com/googollee/go-engine%2eio.(*session).NextReader(0xc00029f130, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/gopath/src/github.com/googollee/go-engine.io/session.go:84 +0x204
github.com/googollee/go-socket.io/parser.(*Decoder).DecodeHeader(0xc00007ccc0, 0xc0006adfa0, 0xc00044c000, 0x0, 0x0)
	/home/gopath/src/github.com/googollee/go-socket.io/parser/decoder.go:58 +0x6d
github.com/googollee/go-socket%2eio.(*conn).serveRead(0xc00012cc00)
	/home/gopath/src/github.com/googollee/go-socket.io/conn.go:180 +0x10c
created by github.com/googollee/go-socket%2eio.(*conn).connect
	/home/gopath/src/github.com/googollee/go-socket.io/conn.go:99 +0x28a

**Comment by tdaajames** [comment]
Still panic here,  I guess other place write web socket without protection...

goroutine 13334 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0004fdce0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/share/gopath/src/github.com/gorilla/websocket/conn.go:597 +0xac3
github.com/gorilla/websocket.(*messageWriter).Close(0xc0004fdce0, 0x0, 0x0)
	/home/share/gopath/src/github.com/gorilla/websocket/conn.go:711 +0x80
github.com/gorilla/websocket.(*Conn).beginMessage(0xc0005c2000, 0xc000578c00, 0x1, 0x0, 0x0)
	/home/share/gopath/src/github.com/gorilla/websocket/conn.go:460 +0x71
github.com/gorilla/websocket.(*Conn).NextWriter(0xc0005c2000, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/share/gopath/src/github.com/gorilla/websocket/conn.go:500 +0xb0
github.com/googollee/go-engine.io/transport/websocket.wrapper.NextWriter(0xc0005c2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/share/gopath/src/github.com/googollee/go-engine.io/transport/websocket/wrapper.go:50 +0xfe
github.com/googollee/go-engine.io/packet.(*encoder).NextWriter(0xc000721a50, 0x7fdda70f3f00, 0x3, 0x0, 0x0, 0x0, 0x0)
	/home/share/gopath/src/github.com/googollee/go-engine.io/packet/encoder.go:20 +0x81
github.com/googollee/go-engine%2eio.(*session).nextWriter(0xc000234370, 0x0, 0x3, 0x0, 0x0, 0x0, 0x0)
	/home/share/gopath/src/github.com/googollee/go-engine.io/session.go:155 +0xb8
github.com/googollee/go-engine%2eio.(*session).NextReader.func1(0xc000234370, 0x1002e00, 0x11536a0, 0xc000578bd0, 0x0, 0x0)
	/home/share/gopath/src/github.com/googollee/go-engine.io/session.go:78 +0x73
github.com/googollee/go-engine%2eio.(*session).NextReader(0xc000234370, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/share/gopath/src/github.com/googollee/go-engine.io/session.go:84 +0x204
github.com/googollee/go-socket.io/parser.(*Decoder).DecodeHeader(0xc000300380, 0xc000797fa0, 0xc0006aa0c0, 0x0, 0x0)
	/home/share/gopath/src/github.com/googollee/go-socket.io/parser/decoder.go:58 +0x6d
github.com/googollee/go-socket%2eio.(*conn).serveRead(0xc00001f5c0)
	/home/share/gopath/src/github.com/googollee/go-socket.io/conn.go:180 +0x10c
created by github.com/googollee/go-socket%2eio.(*conn).connect
	/home/share/gopath/src/github.com/googollee/go-socket.io/conn.go:99 +0x28a
